// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH1gSLWzUPYuZeF523wE8eM3iCUqSje0A',
    appId: '1:735951371475:web:83c0a95a5b25b6afe2e826',
    messagingSenderId: '735951371475',
    projectId: 'event-47a2d',
    authDomain: 'event-47a2d.firebaseapp.com',
    storageBucket: 'event-47a2d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH1gSLWzUPYuZeF523wE8eM3iCUqSje0A',
    appId: '1:735951371475:android:83c0a95a5b25b6afe2e826',
    messagingSenderId: '735951371475',
    projectId: 'event-47a2d',
    storageBucket: 'event-47a2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH1gSLWzUPYuZeF523wE8eM3iCUqSje0A',
    appId: '1:735951371475:ios:83c0a95a5b25b6afe2e826',
    messagingSenderId: '735951371475',
    projectId: 'event-47a2d',
    storageBucket: 'event-47a2d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationEvent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH1gSLWzUPYuZeF523wE8eM3iCUqSje0A',
    appId: '1:735951371475:macos:83c0a95a5b25b6afe2e826',
    messagingSenderId: '735951371475',
    projectId: 'event-47a2d',
    storageBucket: 'event-47a2d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationEvent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH1gSLWzUPYuZeF523wE8eM3iCUqSje0A',
    appId: '1:735951371475:windows:83c0a95a5b25b6afe2e826',
    messagingSenderId: '735951371475',
    projectId: 'event-47a2d',
    storageBucket: 'event-47a2d.firebasestorage.app',
  );
} 