name: flutter_application_event
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.3
  # cloud_firestore: ^5.5.0  # (optional: comment out if not using Firestore)
  firebase_database: ^11.3.7
  
  # State Management
  provider: ^6.1.2
  
  # UI Components
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  
  # Date & Time
  timezone: ^0.10.1
  
  # Icons
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
